### ISSUE TITLE
Example script does not work as expected

### ISSUE THREAD

**Issue by rsholmes** [samschott/desktop-notifier#175]
* Desktop Notifier version: 5.0.1
* Python version: 3.10.12
* Operating System: Linux Mint 21.2

### Description

Tried to use second example from Usage section of README.

Notification lacks the options dropdown shown in the GIF, notification disappears but nothing else happens (and script does not terminate) on dismissing the notification, and message is printed and notification disappears but nothing else happens (and script does not terminate) on clicking the button or the notification.

I expected to see the options dropdown, and I expected the script to terminate after interacting with the notification.

### What I Did

Copied and pasted the example into `n.py` and did `python n.py`. Output depends on what  I do in the notification but script never terminates. I used `^C` to stop the script.

```
$ python n.py     # clicked button
Marked as read
^C$ python n.py   # clicked notification
Notification clicked
^C$ python n.py   # dismissed notification
^C$ 
```

**Comment by samschott** [comment]
> I expected to see the options dropdown

Unfortunately, the supported features vary depending on the platform. The example GIF was recorded on MacOS, which supports a lot more features than most Linux notification servers. You can find more details on what is supported by which platform at https://desktop-notifier.readthedocs.io/en/latest/background/platform_support.html.

> Output depends on what I do in the notification but script never terminates. I used ^C to stop the script.

That is indeed working as intended from the given example code. Feel free to modify the example to quit on any callback instead of `Control + C`.

**Comment by rsholmes** [comment]
Thanks. That page indicates on_dismissed is supported on Linux. However, as indicated by the behavior shown in my post above, I find dismissing the notification does not result in calling the on_dismissed callback.
