### ISSUE TITLE
[Feature Request] Support for timeouts

### ISSUE THREAD

**Issue by iamkroot** [samschott/desktop-notifier#38]
At least on Linux, the notification spec supports specifying the timeout for every notification. It would be great if this option is exposed to the top-level API as `timeout: int = -1` (-1 means OS default).

## Bonus
For other OSes, maybe this can be implemented by spawning an async Timer task that will clear the notif after expiration.

PS: Thanks for making this project. It is extremely useful to have a singular and _full-featured_ interface for cross-platform notifications! :)

**Comment by samschott** [comment]
I like the idea, though missing native support on macOS (and possibly Windows) will certainly result in less elegant implementations there. Though as you can see from other features, they needn't be supported by all backends to be exposed in the API.

If you'd like to contribute this, I'd gladly review a PR :)

**Comment by iamkroot** [comment]
Realized that the approach in bonus section doesn't work if the timeout value is greater than the OS default; we can't make the OS show the notif for an extended amount of time, can we?

The linked PR therefore only implements this for Linux.

**Comment by iamkroot** [comment]
Not exactly sure how, but [this](https://github.com/jithurjacob/Windows-10-Toast-Notifications) repo manages to implement custom timeouts for windows notifications. It seems to be using `win32gui.CreateWindow` to do so, which is probably different from the Windows API that this package uses. But would be nice if we could also do something similar. Will leave as future work.

**Comment by samschott** [comment]
From a brief look, that project uses the [Shell_NotifyIconA](https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shell_notifyicona) API which is an C win32 instead of Win RT API. It has been around for much longer and seems to require manually closing the notification, but it does not support features such as buttons and response boxes AFAIK.

On macOS, iOS and Windows, the concept seems to be that notifications are shown for a fixed duration determined by the OS and user settings outside of the control of the app. However, they do remain in the "Notification Center" afterwards to scroll through and closing them through OS APIs would remove them from there as well.

I would even argue that we should be good citizens of the platforms and respect their UX choices, so I'm completely fine with supporting timeouts on Linux only :)

**Comment by iamkroot** [comment]
Windows does seem to have native support for timeouts via winrt as implemented in https://github.com/DatGuy1/Windows-Toasts

Leaving it here in case anyone is interested in implementing this.
