### ISSUE TITLE
Docs failing :'( How to change icon ?

### ISSUE THREAD

**Issue by JustAlternate** [samschott/desktop-notifier#61]
* Desktop Notifier version: pip latest version
* Python version: 3.10.9
* Operating System: Arch

Hello, love the project, but i cant agree more with #32 , the readme.md could get a new look.

In the base.py you have all those parameters : 

```python
class Notification:
    """A desktop notification
    :param title: Notification title.
    :param message: Notification message.
    :param urgency: Notification level: low, normal or critical.
    :param icon: URI for an icon to use for the notification or icon name.
    :param buttons: A list of buttons for the notification.
    :param reply_field: An optional reply field/
    :param on_clicked: Callback to call when the notification is clicked. The
        callback will be called without any arguments.
    :param on_dismissed: Callback to call when the notification is dismissed. The
        callback will be called without any arguments.
    :attachment: URI for an attachment to the notification.
    :param sound: Whether to play a sound when the notification is shown.
    :param thread: An identifier to group related notifications together.
    :param timeout: Duration for which the notification in shown.
    """
``` 
but only 8 params are showed in the readme :(

what if i want to change the icon of the notification or if i want my notification to never timed out ?

Is there any way to use a relative path to custom icon ?
Currently using this :
`icon="file:///home/justalternate/Projects/PokeNotif/assets/icon.png"`

Something like this would be cool : 
`icon = "assets/icon.png"`

**Comment by samschott** [comment]
I agree, both the docs and the readme could be more elaborate. That being said, the readme tries to showcase features that are available on most platforms, while some platforms limits how desktop notifications are allowed to behave.

A better overview of options and their platform support is provided here: https://desktop-notifier.readthedocs.io/en/latest/background/platform_support.html.

Since this is an open source project, contributions to the documentation are very welcome!
